apiVersion: v1
kind: Pod
metadata:
  name: sample2
spec:
  containers:
    - name: nginx
      image: nginx
    - name: debug
      image: centos:7
      command:
        - sleep
        - "100000"
        ### Note: In Kunernetes numbers should be quotes.


