apiVersion: v1
kind: Pod
metadata:
  name: security
spec:
  containers:
    - name: readiness
      image: rkalluru/zs01-security
      imagePullPolicy: Always
      securityContext:
        #runAsUser: 1000
        runAsNonRoot: true
---
apiVersion: v1
kind: Pod
metadata:
  name: privileged
spec:
  containers:
    - name: readiness
      image: docker

